FROM php:8.1-fpm

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libicu-dev

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN echo "extension=mysqlnd" >> /etc/php/8.1/cli/php.ini
RUN docker-php-ext-install pdo_mysql
# Установка Laravel
WORKDIR /app


# MySql
RUN docker-php-ext-install mysqlnd


COPY composer.lock composer.json ./
RUN composer install --no-scripts --ignore-platform-reqs -v

# Копирование кода приложения
COPY .. .

# Запуск команды при старте контейнера
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
