version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=draw
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  laravel:
    image: my-laravel-image
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=MySQL-8.0
      - DB_PORT=3306
      - DB_DATABASE=draw
      - DB_USERNAME=root
      - DB_PASSWORD=
